### ISSUE TITLE
Is there a way to enable a specific rust compilation feature ?

### ISSUE THREAD

**Issue by librelois** [chevdor/srtool-actions#10]
Hello,

we would like to implement the `on-chain-release-build` feature for the moonbeam runtime, but I see in the srtool code that this feature is only added for polkadot and kusama.

We use this gh action to release our on-chain runtime, is it possible via this github action to build the runtime by activating this rust compilation feature ?

**Comment by chevdor** [comment]
See #9

**Comment by chevdor** [comment]
@librelois CI should be done shortly and v0.4.0 will be then released, allowing exactly that and with an example for your specific use case. I closing by anticipation but feel free to re-open as needed.
