### ISSUE TITLE
Possibility to override parachain pallet ID

### ISSUE THREAD

**Issue by Kailai-Wang** [chevdor/srtool-actions#11]
Hi there, I'd like to ask if there's a way to override the parachain pallet ID and authorize_upgrade index in this GHA.

I noticed there's `PARACHAIN_PALLET_ID` and `AUTHORIZE_UPGRADE_PREFIX` for subwasm and was wondering if there's a similar thing for srtool-actions. Thanks in advance!

**Comment by Kailai-Wang** [comment]
Thanks.

Sure, I'll try to do it tomorrow

**Comment by chevdor** [comment]
Thanks for [the PR](https://github.com/chevdor/srtool-actions/pull/12) @Kailai-Wang
