### ISSUE TITLE
Passing empty envvar to the build?

### ISSUE THREAD

**Issue by Revolution1** [chevdor/srtool-actions#16]
https://github.com/chevdor/srtool-actions/blob/7091873ccd3367aa53f3b1e6c910606ede95ece5/action.yml#L182

```
-e BUILD_OPTS -e PARACHAIN_PALLET_ID -e AUTHORIZE_UPGRADE_PREFIX
```

why?

**Comment by chevdor** [comment]
What you mentioned:
```
-e BUILD_OPTS -e PARACHAIN_PALLET_ID -e AUTHORIZE_UPGRADE_PREFIX
```

is **not** passing empty ENV to the container when running the `build` command.

```
docker run -e FOO SOME_IMAGE
```
is another way to write:
```
docker run -e FOO=$FOO SOME_IMAGE
```

Here is how you can check what I am stating:
```
FOO=bar
docker run --rm -it -e FOO ubuntu echo "$FOO"
docker run --rm -it -e FOO=$FOO ubuntu echo "$FOO"
```

will both return `bar`.

The reason for the missmatch is historical.
A PR introduced the shorter notation and did not take the risk to modify the other ENV.
We could make a PR to have eveything short but that does not bring much **and require some testing** to ensure there is no sneaky behavior :)

**Comment by chevdor** [comment]
You should not need to pass credentials if you use `srtool` directly (or `srtool-cli`) or `srtool-actions`.

As you can see in the [examples](https://github.com/chevdor/srtool-actions/blob/master/examples/01_basic.yml), the GHA does NOT perform the checkout (this is likely where you need creds). Instead the GHA assumes you did whatever is required to bring the code locally (usually an `actions/checkout`).

In your GH workflow, you need to checkout your repo. This is evetually where you'd need credentials.
After that, it is all local and can be handled with `srtool` or `srtool-cli` or `srtool-actions`.

Why would you need to pass credentials to `srtool` ? Please open a new issue with more details on your use case and the errors you run into. I have the feeling it should be working.
