### ISSUE TITLE
need rustc upgrade for polkadot-v1.0.0 para builds

### ISSUE THREAD

**Issue by brenzi** [chevdor/srtool-actions#23]
We currently get this error for srtool build in CI with GHA:

```
  ║ error: `<C as TrieCacheProvider<H>>::Cache<'_>` does not live long enough
728
  ║ --> /home/builder/cargo/git/checkouts/substrate-7e08433d4c370a21/40e3395/primitives/state-machine/src/trie_backend_essence.rs:305:38
729
  ║ |
730
  ║ 305 | let cache = cache.as_mut().map(|c| c as _);
731
  ║ | ^
```

pretty sure this will work if this action bumps rustc to rustc 1.71.0-nightly (9d871b061 2023-05-21)

**Comment by brenzi** [comment]
pardon, just saw that we can customize this

**Comment by chevdor** [comment]
You should really really try NOT to cutomize this... and especially stay with STABLE
